[[gitworkflows]]
== Typical Git workflow using separate repositories

The following description highlights typical Git workflows.

[[gitworkflow_patch]]
=== Providing a patch
(((Git workflow,providing patches)))
Git emphasizes the creation of branches for feature development
or
to create
bug fixes. The following description lists a typical Git
workflow for
fixing a bug in your source code (files) and providing a
patch for it. This patch contains the changes and can be used by
another person to apply the changes to his local Git repository.

This description assumes that the developer who creates the
changes cannot push changes directly to the remote repository. For
example you solve an issue in the source code of an open source
project and want that the maintainer of the project to
integrate this change into this repository.

* Clone the repository, in case you have not done that.
* Create a new branch for the bug fix
* Modify the files (source code)
* Commit changes to your branch 
* Create patch 
* Send patch to another person or attach it to a bug report, so that is can be applied to the other Git repository

You may also want to commit several times during 3. and 4. and
rebase your commits afterwards.

[[gitworkflows_workingwithtworepositories]]
=== Working with two repositories
(((Git workflow,using two repositories)))
Sometimes you want to add a second remote repository to your
local Git repository and pull from and push to both repositories.
The
following example describes how to add another remote
repository
and
exchange commits with both repositories.

You can add another remote repository called
_remote_name_
via the following command.

[source,bourne]
----
include::res/addremote/step1.txt[]
----

For merging the changes in
_mysecondrepo_
create a new branch called
_newbranch_.

[source,bourne]
----
include::res/addremote/step2.txt[]
----

Afterwards you can pull from your new repository called
_mysecondrepo_
and push to your original repository, e.g., origin.

[source,bourne]
----
include::res/addremote/step3.txt[]
----

[[gitworkflows_pullrequests]]
=== Using pull requests
(((Git workflow,providing pull requests)))
Another very common Git workflow is the usage of pull requests.
In this workflow a developer clones a repository and once he thinks
he
has something useful for another clone or the origin repository he
sends the owner a pull request asking to merge his changes.

A pull request can be seen as a notification which includes
the
information from which branch and URL the changes can be pulled
and
also the information to which URL and branch these changes should
be
pulled too.

This workflow is actively promoted by the GitHub.com
hosting
platform but you can also provide the required information to
someone
via email.

TIP: You can use the
`git request-pull`
command to generate a generic pull request which you may include
into an email.
See
https://www.kernel.org/pub/software/scm/git/docs/git-request-pull.html[Git request-pull]
for details.

