[[maven_installation]]
== Installation of the Maven command line tools

[[maven_requirements]]
=== Downloading and installing Maven

[NOTE]
====
If you plan to use Maven only from within the Eclipse IDE, this installation is not required.
====

In case you want to be able to use Maven from the command line, you need to install the Maven command line support. 

		
For a manual installation you can download Maven from the http://maven.apache.org/download.cgi[Maven Download] page.
Extract the downloaded distribution to a selected folder on your computer and add the `M2_HOME` environment pointing to this directory. 
Add `M2_HOME/bin` to your path variable. 

See http://maven.apache.org/download.html#Installation[Maven installation description] for a detailed installation guide.
	
[[maven_installationubuntu]]
=== Ubuntu
		
For Linux most distributions include Maven into their main repositories.
On Ubuntu you can use the following command on the command line to install it. 

[source]
----
include::res/install/install.txt[]
----
		
[[maven_installation_validate]]

=== Validate installation
		
To validate that Maven was correctly installed, open a console and use the following command:
		
[source]
----
include::res/validateinstallation/version.txt[]
----

You should receive as output feedback which version of Maven you have installed.
		
