== Maven Wrapper


You can create a wrapper script which downloads automatically the correct version of Maven.
This way users do not need to install Maven on their local machine.

=== Creating a Maven Wrapper

Create a Maven Wrapper for a project with the latest available Maven version.

[source, Console]
----
cd {your-project}
mvn -N io.takari:maven:wrapper
----

Create a Maven Wrapper for a project with a specified Maven version by using the maven property.

[source, Console]
----
cd {your-project}
mvn -N io.takari:maven:wrapper -Dmaven=3.3.0
----

When wrapper goal has been executed the following files will be created in the maven project.


* mvnw (shell script for unix systems)
* mvnw.cmd (batch file for windows)
* .mvn/wrapper/maven-wrapper.jar (Maven Wrapper JAR)
* .mvn/wrapper/maven-wrapper.properties (Maven Wrapper properties)


[TIP]
====
These Maven Wrapper files should be checked in into version control (e.g. GIT or SVN), so that others who checkout the sources are able to build the projects without the need to install Maven manually in the first place.
And when using the Maven Wrapper there is no need to worry about the right version of Maven, since the project's Wrapper already specifies and downloads it automatically.
====


[NOTE]
====
The `-N`, `--non-recursive` command line option specifies that only the project in the current directory is built without building it's submodules. So the Maven Wrapper will only be applied for the main project and not in every submodule.
====


=== Executing a Maven Wrapper

To run the Maven Wrapper the mvnw for unix systems or mvnw.bat for windows systems can be used.

UNIX:

[source, Console]
----
./mvnw clean package
----

WINDOWS:

[source, Console]
----
mvnw.cmd clean package
----

