[[exercise_maven]]
== Exercise: Create and build a Java project with Maven

In this exercise you create a Java project with the Maven command line and build this project.

[[exercise_maven_generation]]
=== Project generation
		
In this project we use the scaffolding functionality of Maven to create a Java project.
To avoid the interactive mode, all required properties are passed directly to the command. 
Otherwise Maven asks for all the required parameters.
Enter the following into one line in the command shell(the backslash masks the line breaks).

[source,console]
----
include::res/excercise_maven/generate.txt[]
----
		
With this command Maven generates a Java project.

[NOTE]
====
If this is the first time you execute this goal, this may takes some time. 
It also produces additional output compared to a second run.
This is because Maven first loads all required plug-ins and artifacts for the project generation from the Maven central repository.
====	

[[exercise_maven_review]]
=== Review generated project
		
Validate that Maven generated a project on your file system similar to the following structure.
		
[source,console]
----
include::res/excercise_maven/filestructure.txt[]
----
		
You have generated a whole Maven project structure with Java source code.
Maven created a App.java class in the _./src/main/_ folder, which is just a simple "Hello World" program.
It also created an example test class in _./src/test/_.
In the root folder there is a _pom.xml_	file.

[source,console]
----
include::res/excercise_maven/pom.xml[]
----	

[[exercise_maven_compile]]
=== Compile your sources

Now you want to compile your Java sources. 
For this switch on the command line into our projects root directory and trigger the following Maven command.

[source,console]
----
include::res/excercise_maven/compile.txt[]
----	
		
Maven now runs through all life cycle phases, which were needed by the `compile` phase. 
It resolves the dependencies, loads the JUnit artifact and built the sources. 
It even executed the JUnit test.

[[exercise_maven_package]]
=== Create a JAR file

Now you want to create an executable JAR file out of our project. 
The `package` goal creates a deployable JAR file.

To ensure previous build artifacts are removed, you can use the `clean` goal.
		
[source,console]
----
mvn clean package
----

Afterwards you can run the packed program. 

[source,console]
----
include::res/excercise_maven/execute_result.txt[]
----
		
[source,console]
----
include::res/excercise_maven/package.txt[]
----
	
=== Running the test 

Instead of running a full build with packaging, it is also possible to just run the test phases of the Maven life cycle.
		
[source,console]
----
include::res/excercise_maven/test.txt[]
----

=== Remove all build results / Clean the project 

To clean the project and so remove the generated files in the _./target/_ folder, run the following command.

[source,console]
----
include::res/excercise_maven/clean.txt[]
----		

