[[setup]]

== Different levels of Git configuration

[[setup_configurationlevels]]

=== Git configuration levels

The `git config` command allows you to configure your Git settings.
These settings can be system wide, user or repository specific.

A more specific setting overwrites values in the previous level, i.e., a
setting the repository overrides the user setting and a user setting
overrides a system wide setting.

[[setup_systemwideconfiguration]]

=== Git system-wide configuration

(((System wide Git configuration)))

(((Configuration, System wide configuration)))

You can provide a system wide configuration for your Git settings. A system wide configuration is not
very common, most settings are user specific or repository specific as
described in the next chapters.

On a Unix based system Git uses the `/etc/gitconfig` file for this
system-wide configuration. To set this up, ensure you have sufficient
rights, i.e. root rights, in your OS and use the `--system` option for
the `git config` command.

[[setup_userconfiguration]]

=== Git user configuration

(((Configuration, User specific configuration)))
(((User specific Git configuration )))

Git allows you to store user settings in
the `.gitconfig` file located in the user home directory. This is also
called the _global_ Git configuration.

For example Git stores the committer and author of a change in each
commit. This and additional information can be stored in the Git user
settings.

In each Git repository you can also configure the settings for this
repository. User configuration is done if you include the `--global`
option in the `git config` command.

(((Configuration, repository specific configuration)))

[[setup_configuration]]

=== Repository specific configuration

(((Configuration, Repository specific configuration)))
(((Repository specific Git configuration )))

You can also store repository specific settings in the `.git/config` file of a repository.
Use the `--local` or use no flag at all. If neither the `--system` not
the `--global` parameter is used, the setting is specific for the
current Git repository.
