[[firstgit_addfiles]]

= Getting started with Git

[[firstgit_addingfilestarget]]

== Target of this chapter

In this chapter you create several files and place them under version
control.

[[firstgit_content]]

== Create new content

Use the following commands to create several new files.

[source,terminal]
----
include::./examples/commandline/first.commands[]
---- 

[[firstgit_repostatus]]
== See the current status of your repository

((git status))

The `git status` command
shows the working tree status, i.e. which files have changed, which are
staged and which are not part of the staging area. It also shows which
files have conflicts and gives an indication what the user can do with
these changes, e.g., add them to the staging area or remove them, etc.

Run it via the following command.

[source,terminal]
----
include::./examples/commandline/first.status[]
---- 

The output looks similar to the following listing.

[source,terminal]
----
include::./examples/commandline/first.output[]
---- 

== Add files to the staging area \{#firstgit_repoadd}

((git add))

Before committing changes to a
Git repository you need to mark the changes that should be committed.
This is done by adding the new and changed files to the staging area.
This creates a snapshot of the affected files.

[source,terminal]
----
include::./examples/commandline/gitrepo_add[]
---- 

Afterwards run the `git status` command again to see the current
status.

[source,terminal]
----
include::./examples/commandline/gitrepo_add.result[]
----
 
[[firstgit_changefiles]]
== Change files that are staged

In case you change one of the staged files before committing, you need
to add it again to the staging area to commit the new changes. This is
because Git creates a snapshot of these staged files. All new changes
must again be staged.

[source,terminal]
----
include::./examples/commandline/gitrepo_changestaged[]
----

Validate that the new changes are not yet staged.

[source,terminal]
----
include::./examples/commandline/gitrepo_changestaged.result[]
----

Add the new changes to the staging area.

[source,terminal]
----
include::./examples/commandline/gitrepo_add[]
----

Use the `git status` command again to see that all changes are staged.

[source,terminal]
----
include::./examples/commandline/gitrepo_changestaged.finalresult[] 
----


== Commit staged changes to the repository \{#firstgit_repocommit}

((git commit))

After adding the files to the Git staging area, you can commit them to the Git repository. This
creates a new commit object with the staged changes in the Git
repository and the HEAD reference points to the new commit. The `-m`
parameter allows you to specify the commit message. If you leave this
parameter out, your default editor is started and you can enter the
message in the editor.

[source,terminal]
----
include::./examples/commandline/gitrepo_commit[]
----
