[[adjustgitignore]]

= Ignoring certain files and directories

[[usegitignore]]

== Ignore files and directories with the .gitignore file

((.gitignore))
(((gitignore file)))

Git allows you to define pattern for files which
should not be tracked by the Git repository. Create the following
`.gitignore` file in the root of your Git directory to ignore the
specified directory and file.

[source,terminal]
----
include::./examples/remove/gitignorecreate.txt[]
---- 

[[TIP]]
====
The above command creates the file via the command
line. A more common > approach is to use your favorite text editor to
create the file. This > editor must save the file as plain text, e.g.,
gedit under Ubuntu or > Notepad under Windows.
====

The resulting file looks like the following listing.

[source,terminal]
----
include::./examples/remove/gitignore.txt[]
----


== Stop tracking files based on the .gitignore file \{#untrack}

((.gitignore, remove already committed files))

Files that are tracked by Git are
not automatically removed if you add them to a `.gitignore` file. Git
never ignores files which are already tracked, so changes in the
`.gitignore` file only affect new files. If you want to ignore files
which are already tracked you need to explicitly remove them.

The following command demonstrates how to remove the `.metadata`
directory and the `doNotTrackFile.txt` file from being tracked. This is
example code, as you did not commit the corresponding files in your
example, the command will not work in your Git repository.

[source,terminal]
----
include::./examples/remove/remove.txt[] 
----

Adding a file to the `.gitignore` file does not remove the file from the
repository history. If the file should also be removed from the history,
have a look at the `git filter-branch` command which allows you to
rewrite the commit history. See <<filterbranch_definition>> for details.

[[commitgitignore]]

== Commit the .gitignore file

It is good practice to commit the `.gitignore` file into the Git
repository. Use the following commands for this.

[source,terminal]
----
include::./examples/remove/gitignoreaddtorepo.txt[] 
----
