[[gitclone]]
= Cloning repositories and the remote called "origin"

[[remotes_cloneoperation]]
== Cloning a repository

((Repository))

LARSSECONDARY"clone"LARSSECONDARY (((git
clone)))

 The `git clone` command copies an existing Git
repository. This copy is a working Git repository with the complete
history of the cloned repository. It can be used completely isolated
from the original repository.

[[remotes_clone_origin]]
== The remote called "origin"

((origin))
 LARSSECONDARY""LARSSECONDARY If
you clone a repository, Git implicitly creates a _remote_ named _origin_
by default. The _origin_ _remote_ links back to the cloned repository.

If you create a Git repository from scratch with the `git init` command,
the _origin_ remote is not created automatically.

[[remotes_setupexercise]]
== Exercise: Cloning to create a bare Git repository

In this section you create a bare Git repository. In order to simplify
the following examples, the Git repository is hosted locally in the
filesystem and not on a server in the Internet.

Execute the following commands to create a bare repository based on your
existing Git repository.

[source,terminal] ----
include::./examples/commandline/git_remote.commands[] ---- > *Tip* > >
If you receive a warning similar to the following: >
`push.default is unset; its implicit >                     value >                     is changing in >                     Git 2.0 >                     from 'matching' to 'simple'`,
see ? for the > missing configuration.
