[[remotes]]

= Adding and listing existing remotes

[[remotes_remoteadd]]

== Adding a remote repository

(((Repository, add more remote repositories)))

You add as many _remotes_ to your repository as
desired. For this you use the `git remote add` command.

You created a new Git repository from scratch earlier. Use the following
command to add a remote to your new bare repository using the _origin_
name.

[source,terminal]
----
include::./examples/remoteadd/gitremoteadd.txt[]
---- 

[[remotes_remote_synchronize]]
== Synchronizing with remote repositories

((Synchronize repositories more remotes))

You can synchronize your local Git repository with remote repositories.
These commands are covered in detail in later sections but the following
command demonstrates how you can send changes to your remote repository.

[source,terminal]
----
include::./examples/remoteadd/gitremotepush.txt[]
---- 

[[remotes_showremote]]

== Show the existing remotes

(((Repository, show existing remotes)))

To see the existing definitions of the remote repositories, use the following command.

[source,terminal]
----
include::./examples/remote/show.txt[]
----

To see the details of the _remotes_ , e.g., the URL use the following command.

[source,terminal]
----
include::./examples/remote/showdetails.txt[] 
----
