[[cloneremotes]]

= The push and pull commands

[[cloneremotes_push]]

== Push changes to another repository

(((push)))
(((git push)))

The `git push` command allows you to send data to
other repositories. By default it sends data from your current branch to
the same branch of the remote repository.

By default you can only push to bare repositories (repositories without
working tree). Also you can only push a change to a remote repository
which results in a fast-forward merge. See ? to learn about fast-forward
merges.

See <<gitpushbranch>> for details on pushing branches or the
https://www.kernel.org/pub/software/scm/git/docs/git-push.html[Git push
manpage] for general information.

[[cloneremotes_pull]]

== Pull changes

(((pull)))
(((git pull)))

The `git pull` command allows you to get the
latest changes from another repository for the current branch.

The `git pull` command is actually a shortcut for `git fetch` followed
by the `git merge` or the `git rebase` command depending on your
configuration. In ? you configured your Git repository so that
`git pull` is a fetch followed by a rebase. See ? for more information
about the fetch command.

[[exercise_cloneremotes_clone]]

== Exercise: Clone your bare repository

((Clone repository))

In this exercise you create a Git repository based on the bare repository you created in ? .

Clone a repository and checkout a working tree in a new directory via
the following commands.

[source,terminal]
----
include::./examples/commandline/git_clone.commands[]
----

[[exercise_cloneremotes_push]]

== Exercise: Using the push command

Make some changes in your local repository and push them from your first
repository to the remote repository via the following commands.

[source,terminal]
----
include::./examples/commandline/git_push.commands[]
----
 
[[exercise_cloneremotes_pull]]
== Exercise: Using the pull command

To test the `git pull` in your example Git repositories, switch to your
second repository, pull in the recent changes from the remote
repository, make some changes, push them to your remote repository via
the following commands.

[source,terminal]
----
include::./examples/commandline/git_pull.txt[]
---- 

You can pull in the changes in your first example repository with the following commands.

[source,terminal]
----
include::./examples/commandline/git_pull2.txt[]
----
