[[exercise_workingwithremotes]]
== Exercise: Working with a (local) remote repository

This exercise is based on <<firstgit>>.
You now create a local bare repository based on your existing Git repository.
In order to simplify the examples, the Git repository is hosted locally in the filesystem and not on a server in the Internet.

Afterwards you pull from and push to your bare repository to synchronize changes between your repositories.

[[remotes_setupexercise]]
=== Create a bare Git repository via the clone operation

Execute the following commands to create a bare repository based on your existing Git repository.

[source,console]
----
include::./res/commandline/git_remote.commands[]
----

[[remotes_remoteadd]]
=== Exercise: Clone your bare repository

Clone your bare repository and checkout a working tree in a new directory via the following commands.

[source,console]
----
include::./res/commandline/git_clone.commands[]
----

[[exercise_cloneremotes_push]]
=== Exercise: Using the push command

Make some changes in one of your non-bare local repositories and push them to your bare repository via the following commands.

[source,console]
----
include::./res/commandline/git_push.commands[]
----
 
[[exercise_cloneremotes_pull]]
=== Exercise: Using the pull command

To test the `git pull` in your example Git repositories, switch to other non-bare local repository.
Pull in the recent changes from the remote repository.
Afterwards make some changes and push them again to your remote repository.

[source,console]
----
include::./res/commandline/git_pull.txt[]
---- 

You can pull in the changes in your first example repository with the following commands.

[source,console]
----
include::./res/commandline/git_pull2.txt[]
----

