[[exercise_workingwithremotes]]
== Exercise: Working with a (local) remote repository

[[exercise_cloneremotes_clone]]

=== Target of this exercise

In this exercise you create more Git repositories via the clone operation. 
This is based on <<firstgit>>. 
Afterwards you pull from and push to your bare repository to synchronize changes between your remote repositories.

[[remotes_setupexercise]]
=== Exercise: Cloning to create a bare Git repository

In this section you create a bare Git repository. 
In order to simplify the examples, the Git repository is hosted locally in the filesystem and not on a server in the Internet.

Execute the following commands to create a bare repository based on your existing Git repository.

[source,terminal]
----
include::./examples/commandline/git_remote.commands[]
----

[TIP]
====
If you receive a warning similar to the following: 
`push.default is unset; its implicit value is changing in Git 2.0 from 'matching' to 'simple'`, 
see <<gitsetup_pushconfiguration>> for the missing configuration.
====

[[remotes_remoteadd]]


=== Exercise: Clone your bare repository

Clone your existing repository and checkout a working tree in a new directory via
the following commands.

[source,terminal]
----
include::./examples/commandline/git_clone.commands[]
----

[[exercise_cloneremotes_push]]

=== Exercise: Using the push command

Make some changes in your local repository and push them from your first
repository to the remote repository via the following commands.

[source,terminal]
----
include::./examples/commandline/git_push.commands[]
----
 
[[exercise_cloneremotes_pull]]
=== Exercise: Using the pull command

To test the `git pull` in your example Git repositories, switch to your
second repository, pull in the recent changes from the remote
repository, make some changes, push them to your remote repository via
the following commands.

[source,terminal]
----
include::./examples/commandline/git_pull.txt[]
---- 

You can pull in the changes in your first example repository with the following commands.

[source,terminal]
----
include::./examples/commandline/git_pull2.txt[]
----
