[[gitbranchfiles]]
= Working with branches

[[gitbranch_untrackedfiles]]
== Switching branches with untracked files

(((switch branch, with untrack files)))

Untracked files (never added to the staging
area) are unrelated to any branch. They exist only in the working tree
and are ignored by Git until they are committed to the Git repository.
This allows you to create a branch for unstaged and uncommitted changes
at any point in time.

[[gitbranch_dirtyfiles]]
== Switching branches with uncommitted changes

(((switch branch,with uncommitted changes)))

Similar to untracked files you can switch branches with unstaged or staged modifications which are not yet committed.

You can switch branches if the modifications do not conflict with the files from the branch.

If Git needs to modify a changed file during the checkout of a branch,
the checkout fails with a "checkout conflict" error. This avoids that
you lose changes in your files.

In this case the changes must be committed, reverted or stashed (see <<stash_usage1>>). 
You can also always create a new branch based on the current HEAD.
