[[tags]]
= Tags in Git

[[tagging]]
== What are tags?

((Tags/Tagging))
 Git has the option to
_tag_ a commit in the repository history so that you find it easier at a
later point in time. Most commonly, this is used to tag a certain
version which has been released.

If you tag a commit, you create an annotated or lightweight tag.

[[tagging_lightweight_annotated]]
== Lightweight and annotated tags

Git supports two different types of tags, lightweight and annotated
tags.

A _lightweight tag_ ((Tags/Tagging))

LARSSECONDARY"lightweight tag"LARSSECONDARY is a pointer to a commit,
without any additional information about the tag. An _annotated tag_
((Tags/Tagging))
 LARSSECONDARY"annotated
tag"LARSSECONDARY contains additional information about the tag, e.g.,
the name and email of the person who created the tag, a tagging message
and the date of the tagging. _Annotated tags_ can also be signed and
verified with _GNU Privacy Guard (GPG)_ .

[[tagging_namingconventions]]
== Naming conventions for tags

((Tags/Tagging))
 LARSSECONDARY"naming
conventions"LARSSECONDARY Tags are frequently used to tag the state of a
release of the Git repository. In this case they are typically called
_release tags_ .

Convention is that release tags are labeled based on the
[major].[minor].[patch] naming scheme, for example "1.0.0". Several
projects also use the "v" prefix.

The idea is that the _patch_ version is incremented if (only) backwards
compatible bug fixes are introduced, the _minor_ version is incremented
if new, backwards compatible functionality is introduced to the public
API and the _major_ version is incremented if any backwards incompatible
changes are introduced to the public API.

For the detailed discussion on naming conventions please see the
following URL: http://semver.org/[Semantic versioning] .
