[[tagging]]
== Working with tags

[[tagging_list]]
=== List tags

(((Tags/Tagging, list available tags)))
You can list the available tags via the following command:

[source,terminal]
----
include::./examples/tag/list.txt[]
----

[[tag_searchbypattern]]
=== Search by pattern for a tag

You can use the `-l` parameter in the `git tag` command to search for a pattern in the tag.

[source,terminal]
----
include::./examples/tag/search.txt[]
----

[[tagging_createlightweight]]
=== Creating lightweight tags

(((Tags/Tagging, create lightweight tags)))
To create a lightweight tag don't use the `-m` , `-a` or `-s` option.

The term _build_ describes the conversion of your source code into
another state, e.g., converting Java sources to an executable `JAR`
file. Lightweight tags in Git are often used to identify the input for a
build. Frequently this does not require additional information other
than a build identifier or the timestamp.

[source,terminal]
----
include::./examples/tag/createlight.txt[]
----

[[tagging_createannoted]]
=== Creating annotated tags

(((Tags/Tagging, create annotated tags)))

You can create a new annotated tag via the
`git tag -a` command. An annotated tag can also be created using the
`-m` parameter, which is used to specify the description of the tag. The
following command tags the current active HEAD.

[source,terminal]
----
include::./examples/tag/create.txt[]
----

You can also create tags for a certain commit id.

[source,terminal]
----
include::./examples/tag/createid.txt[]
----

[[tagging_signedtags]]
=== Creating signed tags

(((Tags/Tagging, signed tags)))

You can use the option `-s` to create a signed tag.
These tags are signed with _GNU Privacy Guard (GPG)_ and can also be
verified with GPG. For details on this please see the following URL:
https://www.kernel.org/pub/software/scm/git/docs/git-tag.html[Git tag
manpage].

[[tagging_checkout]]
=== Checkout tags

(((Tags/Tagging, checkout tags)))
 
If you want to use the code associated with the tag, use:

[source,terminal]
----
include::./examples/tag/checkout.txt[]
----
 >
*Warning* > > If you checkout a tag, you are in the _detached head mode_
and commits > created in this mode are harder to find after you checkout
a branch > again. See ? for details.

[[tagging_pushtags]]
=== Push tags

(((Tags/Tagging, pushtag)))

By default the `git push` command does not transfer
tags to remote repositories. You explicitly have to push the tag with
the following command.

[source,terminal]
----
include::./examples/tag/push.txt[]
----

[[tagging_delete]]
=== Delete tags

(((Tags/Tagging, delete tag)))

You can delete tags with the `-d` parameter. This
deletes the tag from your local repository. By default Git does not push
tag deletions to a remote repository, you have to trigger that
explicitly.

The following commands demonstrate how to push a tag deletion.

[source,terminal]
----
include::./examples/tag/delete.txt[]
----
