== Using Tags

[[tagging]]
=== What are tags?

(((Tags/Tagging)))
Git has the option to _tag_ a commit in the repository history so that you find it easier at a
later point in time. Most commonly, this is used to tag a certain
version which has been released.

If you tag a commit, you create an annotated or lightweight tag.

[[tagging_lightweight_annotated]]
==== Lightweight and annotated tags
(((Tags/Tagging, lightweight tag)))
(((Tags/Tagging, annotated tag)))
Git supports two different types of tags, lightweight and annotated tags.

A _lightweight tag_ is a pointer to a commit, without any additional information about the tag. 
An _annotated tag_ contains additional information about the tag, e.g., 
the name and email of the person who created the tag, a tagging message
and the date of the tagging.
Annotated tags can also be signed and verified with _GNU Privacy Guard (GPG)_.

[[tagging_namingconventions]]
==== Naming conventions for tags
(((Tags/Tagging, naming conventions)))
Tags are frequently used to tag the state of a release of the Git repository. 
In this case they are typically called _release tags_.

Convention is that release tags are labeled based on the
[major].[minor].[patch] naming scheme, for example "1.0.0". Several
projects also use the "v" prefix.

The idea is that the _patch_ version is incremented if (only) backwards
compatible bug fixes are introduced, the _minor_ version is incremented
if new, backwards compatible functionality is introduced to the public
API and the _major_ version is incremented if any backwards incompatible
changes are introduced to the public API.

For the detailed discussion on naming conventions please see the following URL: http://semver.org/[Semantic versioning].


[[tagging_list]]
=== List tags
(((Tags/Tagging, list available tags)))
You can list the available tags via the following command:

[source,console]
----
include::res/tag/list.txt[]
----

[[tag_searchbypattern]]
=== Search by pattern for a tag

You can use the `-l` parameter in the `git tag` command to search for a pattern in the tag.

[source,console]
----
include::res/tag/search.txt[]
----

[[tagging_createlightweight]]
=== Creating lightweight tags
(((Tags/Tagging, create lightweight tags)))
To create a lightweight tag don't use the `-m`, `-a` or `-s` option.

The term _build_ describes the conversion of your source code into
another state, e.g., converting Java sources to an executable `JAR`
file. Lightweight tags in Git are often used to identify the input for a
build. Frequently this does not require additional information other
than a build identifier or the timestamp.

[source,console]
----
include::res/tag/createlight.txt[]
----

[[tagging_createannoted]]
=== Creating annotated tags
(((Tags/Tagging, create annotated tags)))
You can create a new annotated tag via the
`git tag -a` command. An annotated tag can also be created using the
`-m` parameter, which is used to specify the description of the tag. The
following command tags the current active HEAD.

[source,console]
----
include::res/tag/create.txt[]
----

You can also create tags for a certain commit id.

[source,console]
----
include::res/tag/createid.txt[]
----

[[tagging_signedtags]]
=== Creating signed tags
(((Tags/Tagging, signed tags)))
You can use the option `-s` to create a signed tag.
These tags are signed with _GNU Privacy Guard (GPG)_ and can also be
verified with GPG. For details on this please see the following URL:
https://www.kernel.org/pub/software/scm/git/docs/git-tag.html[Git tag
manpage].

[[tagging_checkout]]
=== Checkout tags
(((Tags/Tagging, checkout tags)))
If you want to use the code associated with the tag, use:

[source,console]
----
include::res/tag/checkout.txt[]
----
[WARNING]
====
If you checkout a tag, you are in the _detached head mode_
and commits created in this mode are harder to find after you checkout
a branch again. See <<detachedheadmode>> for details.
====

[[tagging_pushtags]]
=== Push tags
(((Tags/Tagging, pushtag)))
By default the `git push` command does not transfer
tags to remote repositories. You explicitly have to push the tag with
the following command.

[source,console]
----
include::res/tag/push.txt[]
----

[[tagging_delete]]
=== Delete tags
(((Tags/Tagging, delete tag)))
You can delete tags with the `-d` parameter. This
deletes the tag from your local repository. By default Git does not push
tag deletions to a remote repository, you have to trigger that
explicitly.

The following commands demonstrate how to push a tag deletion.

[source,console]
----
include::res/tag/delete.txt[]
----

