== Using Tags

(((Tags/Tagging)))
(((Tags/Tagging, lightweight tag)))
(((Tags/Tagging, annotated tag)))
Git has the option to add additional metadata to commits.
This can be used to document for example a commit this is used to perform a software release.

This is done via _tags_.

Git supports two different types of tags, lightweight and annotated tags.

A _lightweight tag_ is a named pointer to a commit, without any additional information about the tag.
An _annotated tag_ contains additional meta data:

* the name and email of the person who created the tag
* tagging message similar to a commit message
* the date of the tagging

Annotated tags can also be signed and verified with _GNU Privacy Guard (GPG)_.


[[tagging_list]]
=== List tags
(((Tags/Tagging, list available tags)))
You can list the available tags via the following command:

[source,console]
----
git tag
----

[[tag_searchbypattern]]
=== Search by pattern for a tag

You can use the `-l` parameter in the `git tag` command to search for a pattern in the tag.

[source,console]
----
include::res/tag/search.txt[]
----

[[tagging_createlightweight]]
=== Creating lightweight tags
(((Tags/Tagging, create lightweight tags)))
To create a lightweight tag don't use the `-m`, `-a` or `-s` option.

The term _build_ describes the conversion of your source code into
another state, e.g., converting Java sources to an executable `JAR`
file. Lightweight tags in Git are often used to identify the input for a
build. Frequently this does not require additional information other
than a build identifier or the timestamp.

[source,console]
----
include::res/tag/createlight.txt[]
----

[[tagging_createannoted]]
=== Creating annotated tags
(((Tags/Tagging, create annotated tags)))
You can create a new annotated tag via the
`git tag -a` command. An annotated tag can also be created using the
`-m` parameter, which is used to specify the description of the tag. The
following command tags the current active HEAD.

[source,console]
----
include::res/tag/create.txt[]
----

You can also create tags for a certain commit id.

[source,console]
----
include::res/tag/createid.txt[]
----

[[tagging_signedtags]]
=== Creating signed tags
(((Tags/Tagging, signed tags)))
You can use the option `-s` to create a signed tag.
These tags are signed with _GNU Privacy Guard (GPG)_ and can also be
verified with GPG. For details on this please see the following URL:
https://www.kernel.org/pub/software/scm/git/docs/git-tag.html[Git tag
manpage].

[[tagging_checkout]]
=== Checkout tags
(((Tags/Tagging, checkout tags)))
If you want to use the code associated with the tag, use:

[source,console]
----
include::res/tag/checkout.txt[]
----
[WARNING]
====
If you checkout a tag, you are in the _detached head mode_
and commits created in this mode are harder to find after you checkout
a branch again. See <<detachedheadmode>> for details.
====

[[tagging_pushtags]]
=== Push tags
(((Tags/Tagging, pushtag)))
By default the `git push` command does not transfer
tags to remote repositories. You explicitly have to push the tag with
the following command.

[source,console]
----
include::res/tag/push.txt[]
----

[[tagging_delete]]
=== Delete tags
(((Tags/Tagging, delete tag)))
You can delete tags with the `-d` parameter. This
deletes the tag from your local repository. By default Git does not push
tag deletions to a remote repository, you have to trigger that
explicitly.

The following commands demonstrate how to push a tag deletion.

[source,console]
----
include::res/tag/delete.txt[]
----

[[tagging_namingconventions]]
=== Using tags for software releases

(((Tags/Tagging, naming conventions)))
Tags are frequently used to tag a software release.
In this case, they are called _release tags_.

Convention is that release tags are labeled based on the [major].[minor].[patch] naming scheme.
These release tags follow the semantic versioning of the software release.

* the _patch_ version is incremented if (only) backwards compatible bug fixes are introduced
* the _minor_ version is incremented if backwards compatible functionality of the user of the public API are introduced
* the _major_ version is incremented if incompatible changes are introduced in the public API


For example "1.0.0" or "v1.0.0".

If software build tools like Maven or Gradle are use, the released version should also follow the semantic versioning.
In this case the tag is typically same as the release version.

See http://semver.org/[Semantic versioning] for more information.


=== Creating of a release log based on tags

Git allows to list the commits between any reference; this includes tags.

This allow to create a release log, for example via the following commands.

[source,console]
----
# show log between two tags
git log tag1..tag1

# show shortlog between two tags
git shortlog tag1..tag1
----




