[[retrievefiles]]
== Retrieving files from the history

=== Create a zip file with the changes files

You can use Git to retrieve the file which were changed.
You can use other command line tools to copy or zip these files.

The command `git ls-files --modified` shows the files which are not yet committed.
`git diff --name-only HEAD^` shows the files changed in the last commit.

For example, the following command zips all changed files which are not yet committed.

[code,terminal]
====
zip modified-files.zip $(git ls-files --modified)
====

[[retrievefiles_show]]
=== View file in different revision
(((git show)))
The `git show` command allows
to see and retrieve files from branches, commits and tags. It allows
seeing the status of these files in the selected branch, commit or tag
without checking them out into your working tree.

By default, this command addresses a file from the root of the
repository, not the current directory. If you want the current directory
then you have to use the ./ specifier. For example to address the
`pom.xml` file the current directory use: `./pom.xml`

The following commands demonstrate that. You can also make a copy of the
file.

[source,console]
----
include::res/show/showrev.txt[]
----
 
[[retrievefiles_fromcommit]]

=== Restore a deleted file in a Git repo

You can checkout a file from the commit. To find the commit which
deleted the file you can use the `git log` or the `git ref-list` command
as demonstrated by the following command.

[source,console]
----
include::res/restore/restoredeletedfile.txt[]
----
 
[[retrievefiles_finddeletedfile]]
== See which commit deleted a file
(((Find commit which deleted a file in Git)))
(((File deletion log in Git)))
The `git log` command allows you to determine which commit deleted a file.
You can use the `--` option in `git log` to see the commit history for a
file, even if you have deleted the file.

[source,console]
----
include::res/show/delete.txt[]
----

