[[undochanges_checkoutcommits]]
== Resetting the working tree based on a commit

[[undochanges_checkoutcommits1]]
=== Checkout based on commits and working tree
((git checkout, based on commit ID))

You can check out arbitrary revisions of your file
system via the git checkout command followed by the commit ID. This
command will reset your complete _working tree_ to the status described
by this commit.

The commit ID is shown if you enter the `git log` command.

The following command shows the log.

[source,console]
----
include::res/commandline/git_checkout1[]
---- 

The following listing shows an example output of a Git log command.

[source,console]
----
include::res/commandline/git_checkout2[]
---- 

[[undochanges_checkoutcommits2]]
== Example: Checkout a commit

To checkout a specific commit you can use the following command.

[source,console]
----
include::res/commandline/git_checkout3[]
----

[WARNING]
====
If you checkout a commit, you are in the _detached
head mode_ and commits in this mode are harder to find after you
checkout another branch. Before committing it is good practice to
create a new branch > to leave the _detached head mode_. See <<detachedheadmode>> for
details.
====

