[[gitremotebranch]]
== Remote and local tracking branches

[[gitremotebranch_overview]]
=== Remote tracking branches

(((Remote-tracking branch)))
Your local Git repository contains references to the state of the branches on the remote repositories to which it is connected. 
These local references are called _remote-tracking branches_.

You can see your remote-tracking branches with the following command.

[source,console]
----
include::res/remotebranch/showremotes.txt[]
----

To update remote-tracking branches without changing local branches you use the `git fetch` command. 
See <<gitfetch>> for more information.

[[gitremotebranch_delete]]
(((Remote tracking branch, delete in local repository)))
It is safe to delete a remote branch in your local Git repository, this does not affect a remote repository.
The next time you run the `git fetch` command, the remote branch is recreated.
You can use the following command for that.

[source,console]
----
include::res/remotebranch/delete.txt[]
---- 


[[gitremotebranch_deleteremote]]
=== Delete a remote branch
(((Remote tracking branch, delete in remote repository)))
To delete the branch in a remote repository use the following command.

[source,console]
----
include::res/remotebranch/deleteremotebranch.txt[]
----

[[git_trackingbranches]]
=== Tracking branches

(((Tracking branch)))
Branches can track another branch. 
This is called _to have an upstream branch_ and such branches can be referred to as _tracking branches_.

_Tracking branches_ allow you to use the `git pull` and `git push` command directly without specifying the branch and repository.

If you clone a Git repository, your local _master_ branch is created as a _tracking branch_ for the _master_ branch of the _origin_ repository
(short: _origin/master_ ) by Git.

You create new _tracking branches_ by specifying the _remote branch_ during the creation of a branch.
The following example demonstrates that.

[source,console]
----
include::res/remotebranch/trackingbranch.txt[]
----

Instead of using the `git checkout` command you can also use the `git branch` command.

[source,console]
----
include::res/remotebranch/create.txt[]
---- 

The `--no-track` allows you to specify that you do not want to track a branch. 
You can explicitly add a tracking branch with the `git branch -u` command later.

[source,console]
----
include::res/remotebranch/update.txt[]
---- 

To see the tracking branches for a remote repository (short: remote) you can use the following command.

[source,console]
----
include::res/remotebranch/showtrackingbranches.txt[]
----

An example output of this might look as follows.

[source,console]
----
include::res/remotebranch/output.txt[]
----

