[[gitfetch]]
== Updating your remote-tracking branches with git fetch

[[gitfetch_intro]]
=== Fetch
(((git fetch)))

The `git fetch` command updates your remote-tracking branches, i.e., it updates the local copy
of branches stored in a remote repository. The following command updates
the remote-tracking branches from the repository called _origin_.

[source,console]
----
include::./res/fetch/fetch.txt[]
----
The fetch command only updates the _remote-tracking branches_ and none of the local branches. 
It also does not change the working tree of the Git repository. 
Therefore, you can run the `git fetch` command at any point in time.

After reviewing the changes in the remote tracking branchm you can merge the changes into your local branches or rebase your local branches onto the remote-tracking branch.

Alternatively you can also use the `git cherry-pick commit_id` command
to take over only selected commits.

See <<cherrypick_definition>> for information about cherry-pick. See <<gitmerge_definition>> for the merge operation
and <<rebase_branches>>. for the rebase command.

[[gitfetch_updateremotes]]
=== Fetch from all remote repositories

The `git fetch` command updates only the remote-tracking branches for one remote repository. 
In case you want to update the remote-tracking branches of all your remote repositories you can use the following command.

[source,console]
----
include::./res/remote/gitupdate.txt[]
----

[[gitfetch_compare]]
=== Compare remote-tracking branch with local branch

The following code shows a few options how you can compare your
branches.

[source,console]
----
include::./res/remotebranch/compare.txt[]
---- 

The above commands show the changes introduced in HEAD compared to origin. 
If you want to see the changes in origin compared to HEAD, you can switch the arguments or use the `-R` parameter.

[[gitfetch_rebase]]
=== Rebase your local branch onto the remote-tracking branch
(((Rebase based on a remote-tracking branch)))

You can rebase your current local branch onto a remote-tracking branch. The following commands demonstrate that.

[source,console]
----
include::./res/remotebranch/apply.txt[]
----

[TIP]
====
More information on the rebase command can be found in <<rebase_branches>>.
====

[[gitremotebranch_fetchpull]]
=== Fetch compared with pull

(((Fetch compared with pull)))

The `git pull` command performs a `git fetch` and `git merge` (or `git rebase` based on your Git settings). 
The `git fetch` does not perform any operations on your local branches. 
You can always run the fetch command and review the incoming changes.
