[[mergeconflict]]
== Exercise: Solving a conflict during a merge operation

[[mergeconflict_examplecreate]]
=== Create a conflict

In the following example you create a conflict during a merge operation.

The following steps create a merge conflict. It assumes that _repo1_ and
_repo2_ have the same _origin_ repository defined.

[source,console]
----
include::./res/merge/createconflict1.txt[]
---- 

[source,console]
----
include::./res/merge/createconflict2.txt[]
----
 
[source,console]
----
include::./res/merge/createconflict3.txt[]
----

As this push would not result in a non-fast-format merge, you receive an error message similar to the following listing.

[source,console]
----
include::./res/merge/createconflict4.txt[]
---- 

To solve this, you need to integrate the remote changes into your local repository. In the following listing the `git fetch` command gets
the changes from the remote repository. 
The `git merge` command tries to integrate it into your local repository.

[source,console]
----
include::./res/merge/createconflict5.txt[]
---- 

This creates the conflict and a message similar to the following.

[source,console]
----
include::./res/merge/createconflict7.txt[]
----

The resulting conflict is displayed in ? and solved in ?

[TIP]
====
If you use the `git pull` command it performs the "fetch and merge" or
the "fetch and rebase" command together in one step. Whether merge or
rebase is used depends on your Git configuration for the branch. See ?
for the global configuration.
====

[[mergeconflict_examplesee]]
=== Review the conflict in the file

Git marks the conflicts in the affected files. In the example from ? one
file has a conflict and the file looks like the following listing.

[source,console]
----
include::./res/merge/mergeconflict.txt[]
---- 

The text above the ======= signs is the conflicting change from your current branch and the text below is the conflicting change from the branch that you are merging in.

[[mergeconflict_examplesolve]]
=== Solve a conflict in a file

In this example you resolve the conflict which was created in ? and
apply the change to the Git repository.

To solve the merge conflict you edit the file manually. The following
listing shows a possible result.

[source,console]
----
include::./res/merge/mergeconflictsolved.txt[]
----

Afterwards add the affected file to the staging area and commit the result.
This creates the merge commit. 
You can also push the integrated changes now to the remote repository.

[source,console]
----
include::./res/merge/createconflict6.txt[]
---- 

Instead of using the `-m` option in the above example you can also
use the `git commit` command without this option. In this case the
command opens your default editor with the default commit message about
the merged conflicts. It is good practice to use this message.

[TIP]
====
Alternatively, you could use the `git mergetool` command.
`git mergetool` starts a configurable merge tool that displays the
changes in a split screen. Some operating systems may come with a
suitable merge tool already installed or configured for Git.
====
