[[submodules]]
== Working with submodules

[[submodules_cloning]]
=== Updating submodules

To pull in changes into a Git repository including the changes in
submodules, you can use the `--recurse-submodules` parameter in the
`git pull command` .

[source,terminal]
----
include::./examples/submodules/pull.txt[]
----
Use the `git submodule update` command to set the submodules to the
commit specified by the main repository.

[source,terminal]
----
include::./examples/submodules/update1.txt[]
----

[WARNING]
====
The fact that submodules track commits and not branches
frequently can lead to confusion. That is why Git 1.8.2 added the option
to track branches. Read the following sections to learn more
about this.
====

[[submodules_trackbranch]]
=== Tracking branches with submodules

Since its 1.8.2 release the Git system allows tracking a branch in a
submodule. To track branches you specify the branch with the `-b`
parameter during the `submodule add` command.

This allows you use to use `--remote` parameter in the
`git submodule update` command.

[source,terminal]
----
include::./examples/submodules/branch.txt[]
----

[[submodules_track]]
=== Tracking commits

Without any additional parameter, submodules are tracked by commit,
i.e., the main Git repository remembers a certain commit of the
submodule.

The `git submodule update` command sets the Git repository of the
submodule to that particular commit. The submodule repository tracks its
own content which is nested into the main repository. This main
repository refers to a commit of the nested submodule repository.

[WARNING]
====
This means that if you pull in new changes into the submodules, you need
to create a new commit in your main repository in order to track the
updates of the nested submodules.
====

If you update your submodule and want to use this update in your main
repository, you need to commit this change in your main repository. The
`git submodule update` command sets the submodule to the commit referred
to in the main repository.

The following example shows how to update a submodule to its latest
commit in its master branch.

[source,terminal]
----
include::./examples/submodules/update.txt[]
----
Another developer can get the update by pulling in the changes and
running the submodules update command.

[source,terminal]
----
include::./examples/submodules/getupdate.txt[]
---- 

[WARNING]
====
With this setup you are tracking commits, so if the
master branch in the submodule moves on, you are still pointing to the
existing commit. You need to repeat this procedure every time you want
to use new changes of the submodules. See <<submodules_trackbranch>> for tracking branches.
====