[[gitpatch_create]]
== Example: Creating patches

[[gitpatch_createandapply]]
=== Create and apply patches
(((Create patch)))
(((git format-patch)))
The following example creates a branch, changes several files and creates a commit recording these changes.

[source,console]
----
include::./res/patch/patch1.txt[]
----
 The
next example creates a patch for these changes.

[source,console]
----
include::./res/patch/patch2.txt[]
----

To apply this patch to your master branch in a different clone of the repository, switch to it and use the `git apply` command.

[source,console]
----
include::./res/patch/patch3.txt[]
----

Afterwards you can commit the changes introduced by the patches and delete the patch file.

[source,console]
----
include::./res/patch/patch4.txt[]
----

[TIP]
====
Use the `git am` command to apply and commit the changes in a single step. 
To apply and commit all patch files in the directory use, for example, the `git am *.patch` command. You specify the order in
which the patches are applied by specifying them on the command line.
====

[[gitpatch_createforcommit]]
=== Create a patch for a selected commit

You can specify the commit ID and the number of patches which should be
created. For example, to create a patch for selected commits based on
the HEAD pointer you can use the following commands.

[source,console]
----
include::./res/patch/patch5.txt[]
----

