[[line_feedendings]]
= Handling line endings on different platforms

[[line_feedendings_platform]]
== Line endings of the different platforms

((line endings))
 (((linefeed
characters)))

 Every time a developer presses return on the
keyboard an invisible character called a line ending is inserted.
Unfortunately, different operating systems handle line endings
differently.

Linux and Mac use different line endings than Windows. Windows uses a
carriage-return and a linefeed character (CRLF), while Linux and Mac
only uses a linefeed character (LF). This becomes a problem if
developers use different operating system to commit changes to a Git
repository.

To avoid commits because of line ending differences in your Git
repository you should configure all clients to write the same line
ending to the Git repository.

[[line_feedendings_convert]]
== Configuring line ending settings as developer

On Windows systems you can tell Git to convert line endings during a
checkout to CRLF and to convert them back to LF during commit. Use the
following setting for this.

[source,terminal]
----
include::./examples/linefeed/windows.txt[]
----
On Linux and Mac you can tell Git to convert CRLF to LF with the
following setting.

[source,terminal]
----
include::./examples/linefeed/linux.txt[]
----
 

==
Configuring line ending settings per repository
\{#line_feedendings_gitattributes}

((.gitattributes ))

LARSSECONDARY""LARSSECONDARY You can also configure the line ending
handling per repository by adding a special `.gitattributes` file to the
root folder of your Git repository. If this file is committed to the
repository, it overrides the `core.autocrlf` setting of the individual
developer.

In this file you can configure Git to auto detect the line endings.

[NOTE]
====
Not all graphical Git tools support the `.gitattributes` file, for
example the Eclipse IDE does currently not support it. See
https://bugs.eclipse.org/bugs/show_bug.cgi?id=342372[Eclipse Bug report]
.
====
