= Technology tutorials from vogella.com

== How to build

In the root directory the following commands can be used to build different outputs.

[source, terminal]
----
// create HTML 5
./gradlew cH

// create PDF
./gradlew cP

// create EPub 3
./gradlew cE

// create All (HTML 5, PDF, EPub 3)
./gradlew cA
----

Alternativly the command can be changed to:

./gradlew -t xx 

this will triger an automatical run of the command once a change is saved in the adoc files.

If these commands are run in the root directory all subprojects will be build.


TIP: Single subprojects can be build when navigating into a subproject and for example run `../gradlew cH`


NOTE: On Windows OS `./gradlew.bat` must be used +
See http://www.vogella.com/tutorials/CSS/article.html[CSS tutorial]

== Create a new tutorial

1. Create a new project(a sub-directory) in the root directory
2. Add the new project to the _settings.gradle_ file (`include '{newProjectName}'`)
3. Open new project in terminal and run `../gradlew cT` to run the `createTemplate` task

== Publish HTML task for Jenkins

Currently the jenkins build server is used to copy the HTML tutorials from an '/output' folder to the actual webserver,
therefore the _publishHtml_ task can be used to create the HTML Tutorials and copy the HTML tutorials to a '/asciidocOutput' folder.
