= Technology tutorials from vogella.com

== How to build

In the root directory the following commands can be used to build different outputs.

[source, terminal]
----
// create HTML 5
./gradlew cH

// create PDF
./gradlew cP

// create EPub 3
./gradlew cE

// create All (HTML 5, PDF, EPub 3)
./gradlew cA
----

If these commands are run in the root directory all subprojects will be build.


TIP: Single subprojects can be build when navigating into a subproject and for example run `../gradlew cH`


NOTE: On Windows OS `./gradlew.bat` must be used +
See http://www.vogella.com/tutorials/Gradle/article.html[Gradle tutorial]

== Create a new tutorial

1. Create a new project(a sub-directory) in the root directory
2. Add the new project to the _settings.gradle_ file (`include '{newProjectName}'`)
3. Open new project in terminal and run `../gradlew iT` to run the `initTemplate` task

== Publish HTML task for Jenkins

Currently the jenkins build server is used to copy the HTML tutorials from an '/output' folder to the actual webserver,
therefore the _publishHtml_ task can be used to create the HTML Tutorials and copy the HTML tutorials to a '/asciidocOutput' folder.

[source, groovy]
----
	task publishHtml(type: Copy, dependsOn: 'createHtml') {
		from "${project.buildDir}/html5"
		into "../build/asciidocOutput/${project.name}"
	}
----