== Installation

To be able to run or compile _Dart_ apps you will need to have the Dart SDK installed.
The SDK can be downloaded from the https://www.dartlang.org/tools/sdk#install[Dart installation website].

Follow the instructions for your operating system.

After that the _Dart SDK_ should be automatically added to your path.

To test this type `dart --version` in a terminal.

=== Other modules

Dart comes with some other modules that may need to be added to the path.

One of them is the https://www.dartlang.org/tools/pub[Dart Package Manager "*Pub*"].
Having it on the path can be handy as it allows you to use packages from the pub registry, similar to _NPM_.

To make all of the extra tools available anywhere, add the folder `<dart-location>/bin` to your path.

TIP: On most Linux distributions and macOS you can find the `<dart-location>` by typing `which dart` into a terminal.

=== Linux

On Linux this is typically in `/usr/lib/dart/bin`.

To add it to your path, simply add `export $PATH:/usr/lib/dart/bin` at the end of the `.bashrc` file in your home directory.

=== MacOS

Add `/Applications/dart/dart-sdk/bin` at the end of `/etc/paths`.

//TODO: Add windows description