[[codereview]]
== Code review
[[codereview_process]]

=== The code review process
(((Code review)))
During a code review process a proposed change is reviewed by other developers. 
Every contributor can suggest changes and update the suggested changes.
Once the change is accepted by a committer, it is merged into the code base.

[NOTE]
====
For an efficient process, the code review should be conducted in a supportive environment where constructive feedback is given to enhance the change.
====

A code review process can be implemented without any tool support. 
But it is typically more efficient, if a structured code review system is used.

Using a code review system, allows to perform an automated test build of the proposed merge.
Continuous integration tools like Jenkins or Hudson can integrate with the review system to find compile errors and to run a test suite.

In general a structured code review process has the following advantages:

* Early error detection:
** Build problems are detected immediately by automatic test builds.
** Logical flaws can be spotted by the human reviewer before any code is merged.
* Alignment with project standards:
** Allows the team to identify early in the process any violations with the team code standards.
** Helps to keep code readable and easier to maintain.
** Allows continuous integration system also checks for code standard conformity automatically as part of the build process.
* Knowledge exchange:
** The code review process allows newcomers to see the code of other more experienced developers.
** Developers can get feedback on their suggested changes.
** Experienced developers can help to evaluate the impact on the whole code.
** Shared code ownership: by reviewing code of other developers the whole team gets a solid knowledge of the complete code base.
* Easy entry to contribution: People without write permission to a repository have an easy way to start contributing and to get feedback.
* Enables review before a change is submitted: Iteration based on review comments / build results happen before a change is merged into the target branch. This result in a cleaner history of the repository.

[[gerrit_explanation]]
=== The Gerrit code review system?
(((Gerrit,definition)))
(((Gerrit,Change)))

https://www.gerritcodereview.com/[Gerrit] is a code review system developed for the Git version control system.
It is a web based code review system, facilitating online code reviews for projects.
Gerrit is a Git server which adds a fine grained access control system and a code review system and workflow.

The user interface of Gerrit is based on _Google Web Toolkit_.
Its uses JGit library to provide the Git functionality.

A developer can use Gerrit to suggest a change. 
Other developers can review the change and suggest improvements.
If a Gerrit change needs improvement, it is possible to update it with a new commit.
Once the suggested changes are accepted, they can be merged to the target branch of the Git repository via the Gerrit user interface.

Gerrit makes code reviews easier by showing changes in a side-by-side display. 
It also supports to display the change as a unified diff which is often easier to read on smaller screens.

A reviewer can add comments to every single line changed.

Gerrit is licensed under the Apache 2.0 license.

The Gerrit review system uses the term _change_, to define a code review / review request. 
Each change is based on one commit.

[[gerrit_centralinfo]]
=== How does Gerrit work?

Gerrit can prevent users from pushing directly to the Git repository.
If you push to Gerrit, you use a certain path ( _ref specification_) which tells Gerrit that you want to create a change.
This push ref specification is _refs/for/master_ if the target of the change under review is the master branch.
You can also push to _refs/for/xyz_ to put a commit into the review queue for the xyz branch.

If you push to this ref specification, Gerrit creates a new change or makes an update of an existing one.
Gerrit uses the _Change-Id_ information in the commit message to identify if the push is a new commit or an update of an existing change.

A change consists of one or more patch sets which are used to improve the first proposal based on review comments.
One patch set corresponds to one Git commit.

It is still possible to bypass code review by pushing directly to _refs/heads/master_ if sufficient rights have been granted.

[[gerrit_votingcategories]]
=== Review categories - Verified and Code-Review

Gerrit supports different categories (also known as labels) for review feedback.
In its default configuration it supports the _Code-Review_ category.

In typical installations also the _Verified_ category is installed.

The _Verified_ category typically means you were able to build and test the change introduced with the Gerrit change.
Typically, this is done by an automated process such as a Jenkins / Hudson build server.

The "Code-Review" category is typically used to vote on the quality of the implementation, code style,  code conformity.
It also indicates that the change is in accordance with the standards desired by the project.

Committers and contributors can vote in these categories. 

[[gerrit_voting]]
=== Voting in Gerrit

The rules for voting in Gerrit is:

* Highest vote (+2 in Code-Review and +1 in Verified) enables submitting
* Lowest vote (-2 in Code-Review) is a veto blocking that the change can be submitted and can't be overruled by other reviewers
* You cannot submit the changes to the Git repository until there is the highest vote in all categories

Typically Gerrit instances uses the _Verified_ and the _Code-Review_ category.

If you did some manual testing and the code works as you desire then it is good to +1 in the "Verified" category.
Or give -1 if it failed some of your use cases that must be resolved in order to merge. 
Otherwise, leave it as 0, if you did not test the code.

Non-committers of the project can vote with -1 and +1 to indicate an opinion in either way.
But ultimately it is up to the decision of those with +2 power to make the overall decision.
You may want to -2 vote to block the submission of the code.
Or vote +2 to indicate that you approve that the contribution is merged into the Git repository.

[[gerrit_drafts]]
=== Posting draft reviews

There is also a special _refs/drafts/master_ refspec which you can use to push changes to for private review before publishing them to all developers.

This is useful if your work is in progress and not ready for public reviews.
You can also CC specific people to review this private change.
Once it is ready for public review there is a _Publish_ button to convert the draft into a change review.


