[[gerrit_installation]]
== Installation of Gerrit

The installation of Gerrit requires the JDK to be installed on the machine.
Also the Git command line tooling must be installed.

[[gerrit_installation_download]]
=== Download Gerrit

(((Gerrit,Installation)))
Download the latest Gerrit release from
http://gerrit-releases.storage.googleapis.com/index.html[Gerrit download page].

The download is a `.war` file.
This war file can run in a servlet container, for example, a Jetty or Tomcat installation.
The `.war` file contains a Jetty web server and can be started directly for testing or rapid deployment. 

The following description starts the Gerrit server directly.

[[gerrit_installation_setup]]
=== Setup of Gerrit

Copy the `.war` file into an empty directory.

Switch on the command line to the location of the directory to which you extracted the `.war` file.
Install Gerrit with the following command.

[source,console]
----
include::res/install/install.txt[]
----

The Gerrit instance is installed into the folder specified with the `-d` parameter, in this example _review_site_.

If you do not use `--batch` flag, you can interactively configure the Gerrit instance via a set of questions.
A few of these options are discussed in the following table.

.Gerrit setup options
[cols="1,3",options="header"]
|===
|Option |Description

|Location of Git repositories
|Location of Git repositories, default is the `git` directory in the installation folder of your Gerrit installation.

|Database server type
|Gerrit supports several databases, by default it uses a preconfigured H2 database.

|Run as user 
|Select that Gerrits runs as "root" user.

|Listen on port 
|Allows you to configure the port Gerrit is listening to, Gerrit by default listens on port 29418 for SSH access and on port 8080 for web access. 
This can be changed if the ports are already used.

|Authentication method 
|Typical configuring to access the Gerrit server uses _LDAP_ or _OpenID Single Sign-on_ which is the default setting. 
Use ? to see all available settings for this option. 
For testing use "development_become_any_account".

|===

[NOTE]
====
Use _development_become_any_account_ to enable general access to Gerrit. 
If started with this setting, you have a _Become_ link in the web interface which allows you to login and to create a new account.
To enable that authentication method, you can use the following command:
git config --file ~/etc/gerrit.config auth.type DEVELOPMENT_BECOME_ANY_ACCOUNT
====

After a successful installation Gerrit starts automatically on Unix-like systems.
You can start and stop it again with the following commands on Linux based systems.

[source,console]
----
include::res/install/start.txt[]
----

On Microsoft Windows based systems you need to invoke the daemon directly. 
From a command shell switch to the folder `gerrit_site` and run the following command to start the server.

[source,batch]
----
include::res/install/windows.txt[]
----

This starts Gerrit.
To stop it again, kill the running process using kbd:[Ctrl+C].


[TIP]
====
If something goes wrong, look into the `logs` folder.
====

[NOTE]
====
The local Gerrit configuration is stored in the `./review_site/etc/` folder.
====
