[[gerrit_installation]]
== Installation of Gerrit

[[gerrit_installation_download]]
=== Download Gerrit
(((Gerrit,Installation)))
Download the latest Gerrit release from
http://gerrit-releases.storage.googleapis.com/index.html[Gerrit download page]. The download is a
`.war`
file which you can directly add to your servlet container, for
example, a Jetty or Tomcat installation.

The
`.war`
file also contains a Jetty web server and can be started directly for
testing or rapid deployment. The following
description uses this approach.


[[gerrit_installation_setup]]
=== Setup of Gerrit

Copy the
`.war`
file into an empty directory.

Switch on the command line to the location of the directory to which
you extracted the
`.war`
file.
Install and start
Gerrit with
the following command.

[source,console]
----
include::res/install/install.txt[]
----

The installation procedure allows you to configure your Gerrit
installation. The installation is done in the folder
specified with
the
`-d`
parameter, in this example "review_site".

The installation procedure asks a few question, pressing enter uses
the default value which is typically fine for a
test installation. A
few of these options are discussed in the following table.

.Gerrit setup options
|===
|Option |Description

|Location of Git repositories
|Location of Git repositories, default is the `git` directory in the installation folder of your Gerrit installation.

|Database server type
|Gerrit supports several databases, by default it uses a preconfigured H2 database.

|Run as user 
|Select that Gerrits runs as "root" user.

|Listen on port 
|Allows you to configure the port Gerrit is listening to, Gerrit by default listens on port 29418 for SSH access and on port 8080 for web access. 
This can be changed if the ports are already used.

|Authentication method 
|The easiest way of
configuring access to Gerrit is to use
_OpenID Single Sign-on_
which is the default setting. Use ? to see all available
settings for this option. For testing
"development_become_any_account" is
a valid option, this setting allows to

|===


TIP: Use _development_become_any_account_ to enable general access to Gerrit. 
This is a nice setting for testing. 
If started with this setting, you have a _Become_ link in the web interface which allows you to login and to create a new account.

After a successful installation Gerrit starts automatically. You
can start and stop it again with the following
commands on Linux
based systems.

[source,console]
----
include::res/install/start.txt[]
----

On Microsoft Windows based systems you need to invoke the
daemon directly. From a command shell switch to the folder
`gerrit_site`
and
run the following command to start the server.

[source,batch]
----
include::res/install/windows.txt[]
----

This starts Gerrit.
To stop it again, kill the running process using
kbd:[Ctrl+C]
If something goes wrong, look into the
`logs`
folder.

TIP: The local Gerrit configuration is stored in the `./review_site/etc/` folder.

