== Developing custom Gradle plug-ins

=== Why creating Gradle plug-ins

As a general rule, it is useful to have a build that is as much declarative as possible as this simplifies future maintenance. 
Therefore it is advised to avoid complex code in your Gradle build file. 
If you need customer logic you should place it, into a custom Gradle plugin.

=== Gradle DSL 

Each Gradle plug-in comes with a DSL. 
To see all properites of a Gradle object, you can use the following code snippet:

[source,code]
----
println variants.properties
            .sort{it.key}
            .collect{it}
            .findAll{!filtered.contains(it.key)}
            .join('\n')
----

For example to define a tasks which show the properties of all `android.applicationVariants` (in an Android project), use:

[source,code]
----
task showAndoidVariantsInformation {
    doLast {
        android.applicationVariants.all { variants ->
        	println variants.properties
            .sort{it.key}
            .collect{it}
            .findAll{!filtered.contains(it.key)}
            .join('\n')
        }
    }
}
----


=== Example: Creating a simple Gradle plugin

To create a custom Gradle plug-in you have to create the following directories for your Gradle project. 
The Java or Groovy directory is only required if you want to use Java or Groovy for writing your plugin.

* projectroot/plugin/src/main/java

* projectroot/plugin/src/main/resources/META-INF/gradle-plugins

* projectroot/plugin/src/main/groovy


Change your main _build.gradle_ build file to the following.

[source,java]
----
include::res/plugin/mainbuild.gradle[]
----


Create a file _vogella.properties_ in the _META-INF/gradle-plugins_ folder. 
The name of the properties file defines your plugin name and its content points to the class which implements the plugin.

[source,java]
----
include::res/plugin/vogella.properties[]
----


In the _plugin/src/main/java_ folder create the following two classes.

[source,java]
----
include::res/plugin/MyPlugin.java[]
----


[source,java]
----
include::res/plugin/MyTask.java[]
----


In your _plugin_ folder, create the following build.gradle file.

[source,java]
----
include::res/plugin/build.gradle[]
----


In your _plugin_ folder, create the following _settings.gradle_ file.

[source,java]
----
include::res/plugin/settings.gradle[]
----

=== Example: Deploy your custom Gradle plug-in to your local Maven repository
Publish your Gradle plug-in to the Maven repo defined in your plugin/build.gradle file via the following command.

[source,java]
----
include::res/plugin/publish.gradle[]
----

=== Example: Using your new plugin
To use your new plug-in, define a dependency to it and a task extending the defined task.
If you pushed your plug-in to your local Maven repository, Gradle should find it and make it available.

[source,java]
----
include::res/plugin/consumer.gradle[]
----



