[[mda_overview]]
== Appendix: Model-Driven Architecture (MDA)

[[mda_overview_s1s2a]]
=== Overview

MDA is the approach in which models are automatically
translated into complete, deployable, running applications.

MDA defines several levels for these models, Platform
independent models, platform specific models and code
models.

[[mda_overview_s1s2b]]
=== Platform Independent Model (PIM)

Represents the business model to be implemented and can be
described via UML. The PIM describes the processes of the
business model and the structure of the system. The PIM does
not specific operating system, programming language and
hardware.

[[mda_overview_s1s2c]]
=== Platform Specific Model (PSM)

The PSM is responsible to specify the technical details to
implement the PIM, e.g. the operating system, the
programming language. In case several realizations /
implementations for a PIM are possible then several PSM are
formulated.

[[mda_overview_s1s2d]]
=== Code Mode

Represents the deployable code. In an ideal MDA scenario
this code could be directly compiled and deployed without
human interaction.

