== Tips

=== Creating a bootable USB disk with unetbootin
		
The default program for creating a bootable USB disk is _Startup Disk Creator_. 
This crashes frequently during the creation of a boot disk. The program _unetbootin_ is much more stable. 
You can install it via the following command and start it on the command line.
		
[source,console]
----
include::res/unity/menu.txt[]
----
		
To open this type "Menu Manager" in the Dash. 
Choose "programming" in the left panel. 
Press "New item" button then. 
Choose name, command, icon
		
In the panel click and hold Alt to quick switch/launch apps.

=== Chat applications
		
The
_mumble_
application
allows online chats.
		
[source,console]
----
include::res/tools/mumble-install.txt[]
----

=== Sharing desktop
		
The _Teamviewer_ application allows to share desktop and online chats. 
It can be installed from http://www.teamviewer.com/.

=== Remote xserver
		
The _x2go_ server allows to install a X-server on a remote server and access it via a client from a different machine.
More information can be found on http://wiki.x2go.org/.

=== Eclipse IDE configuration
		
See http://devblog.virtage.com/2013/06/eclipse-and-eclipse-based-apps-on-ubuntu-13-04-desktop-hacks[Eclipse and Ubuntu] for an introduction into the configuration of the Eclipse IDE under Ubuntu.

