[[docbookpdf]]
== Create pdf output

[[docbookpdf_overview]]
=== Overview

You can convert DocBook to XML-FO via the DocBook XSL
Stylesheets. XML FO stands for XML Formating Objects and is an XML
standard
which is optimized for print media. XML-FO can then be
tranlated into PDF via the Apache FOP library.

[[docbookpdf_installation]]
=== Installation

In addition to the existing setup you also require the Apache
FOP
library. Download the binary FOP distribution from
http://xmlgraphics.apache.org/fop/.

Copy all the JAR files from the FOP distribution in your library
directory
and add the libs to the ant build path. See
http://www.vogella.com/tutorials/ApacheAnt/article.html#classpath[Apache Ant Tutorial]
on how to modify the ant build path.

[[docbookpdf_]]
=== Define the Ant Task

You have to add the task to your ant build file and then call
the task. The following snippet shows how to define the task and how to call
it. The second listing is then a full example ant `build.xml` file.

[source,xml]
----
include::res/ant/pdftask.xml[]
----

[source,xml]
----
include::res/ant/buildpdf.xml[]
----

