[[tools]]
== Derby tools

[[tools_commandline]]
=== Using Derby from the command line (ij)

ij is Derby's interactive JDBC scripting tool. It is a simple
utility for running scripts or interactive queries against a Derby
database. To start the tool open a command shell and type in "ij". This
will start a shell program which can connect to your database and
execute SQL commands .
Stop this tool with typing in "exit;" and pressing enter. In ij
every line need to get terminated via a ;

If you want to connect to the Derby database in
`embedded mode`
you can use the following command. In this example the database is
located at c:\temp\db\FAQ\db

[source,bourne]
----
include::res/ij/connect.txt[]
----

If you want to connect to a Derby database which is running in
`server mode`
then you can use the following command.

[source,bourne]
----
include::res/ij/connectServer.txt[]
----

To disconnect from the database.

[source,bourne]
----
include::res/ij/disconnect.txt[]
----

To run a SQL script from ij use the following command.

[source,bourne]
----
include::res/ij/sqlcommand.txt[]
----

You can also used SQL directly, e.g.

[source,bourne]
----
include::res/ij/select.txt[]
----

[[usage_sqldump]]
=== SQL dump for the database schema

Use the tool dblook. Type dblook on the console to see the
options, the tool is really easy to use. For example to write the
schema "myschema" to the file "lars.sql".

[source,bourne]
----
include::res/dblook/createSchema.txt[]
----

