[[service]]
== Running Derby Server as Windows Service

The Derby Server is started via a batch program. 
In a server environment this batch program should be automatically started if the server is rebooted / started. 
The windows program "srvmgr" can be used for this purpose. 
For details on the tool please check the official documentation; the following will give a description on how this can be done for Apache Derby. 
Install "srvmgr" and remember the installation path. 

We will call our service "ApacheDerby" and the batch file is located under "C:\db-derby\bin\startNetworkServer.bat". 
In the command line register a service via: 

[source,text]
----
include::res/service/installservice.txt[]
----

You should receive a success message. 

[TIP]
====
If something goes wrong and you want to remove an installed service, you can use:

[source,text]
----
include::res/service/removeservice.txt[]
----
====

Run Regedt32.exe and locate the following subkey HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ApacheDerby.

From the Edit menu, select menu:New[Key] and add a key named `Parameters`.

Select the `Parameters` key, that you have just created.
From the Edit menu, select menu:New[String Value] and maintain the following values.

[source,text]
----
include::res/service/keys.txt[]
----

Now start/adjust the service in the Windows services control panel.

