== Introduction to docker

Docker is a light weight container, allowing to run pre-configured system images on another operating system. 
Docker does not virtualize a whole system; a container only includes the packages that are not included in the underlying system.
Docker requires a very small amount of resources, as does not require an hypervisor for each container. 

Docker is an open source project, released under the Apache License, version 2.

Docker allows to package the full stack in a container:

* OS,
* JVM,
* App server
* Application with its configuration

This makes the virtual machine portable  across environments. Developers can use the same setup as you can use in your production environment.

== Use cases

Docker allows to solve the following use cases

* You can to use a specific version of a operating system for testing
* You want to run your software tests in an controlled environment
* You want to configure a system and share the configuration


== Docker components

Docker consists of the following components:

* Images
* Containers
* Daemon
* Clients
* Registries

=== Images

Images are read-only templates which provide functionality for running an instance of this image (container). 
An example for a image is the latest release of Ubuntu. Images are defined as layers, 
for example, you can add Java to the Ubuntu image and get another image based on this.

The Docker hub provides lot of pre-configured images. You can modify existing images and save these modifications as new image. 

=== Containers

Container are the started components based on images. They contain the actual application and dependencies but share the same kernel.
They can be started, stopped, paused, deleted. Containers are immutable and disposable.

=== Docker Daemon

Is used to manage the container. It runs natively on Linux and  inside a VM on Windows and Mac OS X. To start it use the `docker` command.

=== Docker clients

Clients (CLI, IDE) run on host VM. They provide the tools to interact with container, i.e., to start them.

=== Docker registry

Images are saved in a registry and have an ID with consists of a repository and a tag. 
For example, _fedora:22_, is an image which contains the Fedora 22 OS from the fedora repository.

To use an image you have to pull it from a registry, to share an image with others you have to push it to one. The default Docker registry is the Docker Hub. You can upload your personal images to Github, in this case you add your user name as prefix to the image, e.g.,  _vogella/fedore:22_

=== Dockerfile

A dockerfile allows to modify existing images. It contains the image that should be used and the adjustments to this image, e.g., which packages should be installed, system configuration etc. 


