= Exercise: Creating an Ubuntu based Unix system with Java

To run a bash on an Ubuntu 15.04 system, use the following command.
----
docker run -t -i ubuntu:15.04 /bin/bash
----
This creates a docker container (if not yet present), start the Ubuntu system and runs a shell in this container.


You can create your custom Docker images. For this you write a docker file describing your
image. This file is typically named `Dockerfile`.

See https://docs.docker.com/engine/articles/dockerfile_best-practices/[Dockerfile best practices]/

For example the following is a docker file which describes an image based on Ubuntu 15.10 with Java installed.

----
include::examples/ubuntujava/Dockerfile[]
----

To create an Docker image from this file, enter the `docker build -t [imagename]` command. 
If you used for example `ubuntujava8` as image name, you can now start the corresponding container with the
`docker run -t -i ubuntujava8 /bin/bash` command and type in `java` to check if the installation was successfully. 

