== Configuration files in Apache HTTP</title>

The following describes the configuration files and commands for the Apache HTTP web server on Ubuntu.

[[apache_httpcommands]]
=== Important Apache HTTP commands

Use the following command to list the available modules of the Apache HTTP server.

----
/etc/init.d/apache2 -l
----

----
/etc/init.d/apache2 restart
----

[[apachehttp_conffiles]]
=== Configuration Files

The main configuration file for the Apache Http server is the `/etc/apache2/apache2.conf` file.
The error log of Apache is located in the `/var/log/apache2/error.log` file.

[[apachehttp_mpm]]
=== Multi-Processing-Module (MPMs)

Apache HTTP can be running in different modes. 
These modes determine how the web requests of users are answered. 
There are called http://httpd.apache.org/docs/2.4/mpm.html[Multi-Processing-Module (MPMs)].

The selected mode is compiled into the server and can be seen via the following command.

----
sudo apachectl -V | grep -i mpm
----

The configuration for the event mpm is stored in `/etc/apache2/mods-available/mpm_event.conf`. 
Configure only the module which your server is using. 

The following listing shows a configuration for a high traffic web server using the event module

[source]
----
include::examples/snippets/event.txt[]
----
	
=== Checking for Apache HTTP problems

The `error.log` file contains the error messages of the Apache HTTP server. For example to check for too many simultaneous request you can run.

[source]
----
grep MaxClients /var/log/apache2/error.log

// If there are problems you might get something like this:
// server reached MaxClients setting, consider raising the MaxClients setting
----

[[apachehttp_htaccess]]
=== Apache Configuration via .htaccess

Use the file ".htacess" to configure certain behavior of Apache HTTP. 
One major application of this file is to redirect URL to other URL's.

The following .htacess file reroutes that http://vogella.com to http://www.vogella.com. 
It also redirect access to a certain webpage (/articles/SpringFramework/article.html) to another webpage via a 301 redirect. 
The 301 redirect will tell search engines that this side has moved and is the recommended way to move webpages.

[source]
----
include::examples/htaccess_config/htaccess.reroute[]
----

[[apachehttp_modules]]
=== Using modules on Apache Http
Apache Http supports the usage of modules. 
To enable  modules use the `a2enmod` command, e.g. `a2enmod rewrite` to enable the rewrite module.



[[apachehttp_compression]]
=== Performance - Turn on gzip compression

To optimize the download time of your webpages you can turn on gzip compression. 
This requires the Apache module "mod_deflate" which can be installed by the following command:

[source]
----
include::examples/compress2/compress_module.txt[]
----

The compression can be activate in the default configuration file for this module located in /etc/apache2/mods-available/deflate.conf or via your ".htaccess" file.

[source]
----
include::examples/compress2/htaccess.compress[]
----

[[Other Apache modules]]
== Supporting php and wordpress

[source]
----
sudo apt-get install libapache2-mod-fcgid
sudo apt-get install php5-cgi
----

Afterwards activate the corresponding modules.

[source]
----
sudo a2enmod fastcgi
sudo a2enmod proxy
# required for wordpress blog
sudo a2enmod rewrite
----

In case you want to send out emails from your PHP sides you have to configure an email client. 
A simple one is exim4, a setup description can be found under the following links: https://help.ubuntu.com/community/Exim4 and https://wiki.debian.org/GmailAndExim4 

[source]
----
sudo apt-get install exim4
----

Here is an example /etc/exim4/update-exim4.conf.conf file
[source]    
----
dc_eximconfig_configtype='smarthost'
dc_other_hostnames=''
dc_local_interfaces='127.0.0.1 ; ::1'
dc_readhost='gilbert.vogella.com'
dc_relay_domains=''
dc_minimaldns='false'
dc_relay_nets=''
dc_smarthost='smtp.gmail.com:587'
CFILEMODE='644'
dc_use_split_config='true'
dc_hide_mailname='false'
dc_mailname_in_oh='true'
----

You need to enter valid user credentials in the passwd.client file in the following format.

----
*google.com:youruser@gmail.com:yourpassword
----

[[apachehttp_pagespeed]]
=== Using the pagespeed module

You should also install he pagespeed module from Google, as this compresses the content of the website and results in a mucher faster download.
See http://tecadmin.net/install-apache2-with-mod-pagespeed-on-ubuntu/ for the setup.


[[apachehttp_migration]]
=== Migration of servers

In case you are migrating your server from one server to another you can tell your local computer to resolve to the new server, even though you did not yet change the DNS setting. 
This way you can test if the new server works fine. 