== Asciidoc

AsciiDoc is a text document format for writing notes, documentation, articles, books, ebooks, slideshows, web pages, man
pages and blogs. AsciiDoc files can be translated to many formats including HTML, PDF, EPUB, man page.

Any text editor can be used, even Github allows to edit AsciiDoc directly.

=== Asciidoc documents

Asciidoc documents typically ends with the _.adoc_.

=== Install the Asciidoctor toolchain

If you want to use aciidoctor directly you have to install its toolchain. 
If you are using Gradle or Maven as build systems it is not required to install Asciidoctor separately.

[source, terminal]
----
sudo apt-get install -y asciidoctor
----

=== Importing files or file includes

You can import files via the include macro. This also works for source code includes. The \ is only there, as I do not know how 
to include a source file within a source file.

----
[source,java]
\----
\include::examples/source.java[]
\----
----

=== Defining lists

Lists can be define with the *, sublists and use up to 6 *. Ensure to have a space before the list element. Example:
[source, terminal]
....
Docker allows to package the full stack in a container:

* OS
** Windows
** Ubuntu
* JVM,
* App server
* Application with its configuration
....

Result:
====
* OS
** Windows
** Ubuntu
* JVM,
* App server
* Application with its configuration
====


Numbered lists start with the .

....
[source, terminal]
. OS
.. Windows
.. Ubuntu
. JVM,
. App server
. Application with its configuration
....

Result:
====
. OS
.. Windows
.. Ubuntu
. JVM,
. App server
. Application with its configuration
====

=== Menus 

You can define menus with the following syntax.

----
menu:View[Zoom > Reset]
----

The result looks like the following.

menu:View[Zoom > Reset].



=== Using monospace

Use monospace text formatting to emulate how source code appears in computer terminals, 
simple text editors, and integrated development environments (IDEs). 
Enclose a string with ` for this, e.g., \`System.out.println("Hello");` results in `System.out.println("Hello");` 

=== Defining references

You can assign meta data to a block. Here’s an example of a quote block that includes all types of metadata:
....
.This is the title
[[yourId]]
[yourstyle]
____
Four score and seven years ago our fathers brought forth
on this continent a new nation...

Now we are engaged in a great civil war, testing whether
that nation, or any nation so conceived and so dedicated,
can long endure. ...
____
....

This is the title is the title of the block, yourId is a reference for the block and yourstyle can be used to style the corresponding block.
You can link to the references via 
....
<<yourId>>
....

Lets see if that works <<test>>.

[[table]]
=== Table

You can create also tables in Asccidoc via the following syntax.

----
.Table Title
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3 

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===
----

The result looks like the following.

.Table Title
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3 

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===

[[test]]
=== Source code and callouts

To enable syntax highlighting in the output, set the style on the block to source and specify the source language in the second attribute position. 
It is also very simple to add callouts, as demonstrated by the following snippet.

	
....
[source, java, numbered]
----
System.out.println("Hello");  # <1>
private int a;
----
<1> Imports the library
....

Output is the following

[source, java, numbered]
System.out.println("Hello");  # <1>
private int a;

<1> Imports the library

=== Escape special signs

If you need to escape Asciidoc commands, you can use \\{qwe} or \+++{qwe}\+++.

=== Index

You can add primary index terms to your document via +++(((yourterm)))+++. 
A secondary index can be added to your document via +++(((yourterm, secondary term2)))+++. 
For example:

+++((((Big cats)))+++

+++((((Big cats, Lions)))+++



=== Custom attributes / variables

You can define custom variables and use them in your document with \{youridentifier\}. For example the following defines
the variable `contentidentifier` which can be used with \{contentidentifier\} and Asciidoctor will replace 
it with the value defined after the second :.

-----
:contentidentifier: description
-----
