== Asciidoc

AsciiDoc is a text document format for writing notes, documentation, articles, books, ebooks, slideshows, web pages, man
pages and blogs. AsciiDoc files can be translated to many formats including HTML, PDF, EPUB, man page.

Any text editor can be used, even Github allows to edit AsciiDoc directly.

== Asciidoc documents

Asciidoc documents typically ends with the _.adoc_.

== Install the Asciidoctor toolchain

If you want to use aciidoctor directly you have to install its toolchain. 
If you are using Gradle or Maven as build systems it is not required to install Asciidoctor separately.

[source, terminal]
----
sudo apt-get install -y asciidoctor
----

== Importing files

You can import files via the include macro. This also works for source code includes.

DON'T KNOW HOW TO PRESERE the LINE BREAKS in THE HTML output
++++++++
[source,java]
----
\include::examples/source.java[]
----
++++++++

== Defining references

You can assign meta data to a block. Here’s an example of a quote block that includes all types of metadata:
....
.This is the title
[[yourId]]
[yourstyle]
____
Four score and seven years ago our fathers brought forth
on this continent a new nation...

Now we are engaged in a great civil war, testing whether
that nation, or any nation so conceived and so dedicated,
can long endure. ...
____
....

This is the title is the title of the block, yourId is a reference for the block and yourstyle can be used to style the corresponding block.
You can link to the references via 
....
<<yourId>>
....

Lets see if that works <<test>>.

[[test]]
== Source code and callouts

To enable syntax highlighting in the output, set the style on the block to source and specify the source language in the second attribute position. 
It is also very simple to add callouts, as demonstrated by the following snippet.

	
....
[source, java, numbered]
----
System.out.println("Hello");  # <1>
private int a;
----
<1> Imports the library
....

Output is the following

[source, java, numbered]
System.out.println("Hello");  # <1>
private int a;

<1> Imports the library

== Index

You can add primary index terms to your document via ((yourterm)). A secondary index can be added to your document via (((seconddary term1, secondary term2))). 


(((Big cats,Lions)))

++++
(((Big cats,Lions)))
++++

Example 


== Convert to DocBook
To convert asciidoc into DocBook use the following command:

asciidoctor -b docbook45 inputfile.adoc.

== Convert Asciidoc to Docbook

To convert asciidoc into DocBook use the following command:

asciidoctor -b docbook45 inputfile.adoc.

