== Conversion with Asciidoctor

You will need a working Ruby installation. For our installation guide see:
https://www.vogella.com/tutorials/Ruby/article.html

=== Asciidoctor installation

To convert your asciidoc files you need to install the http://asciidoctor.org[Asciidoctor gem].

[source, terminal]
----
gem install asciidoctor
----

If you want to be able to create pdf-files you can use the asciidoctor-pdf gem.

[source, terminal]
----
gem install --pre asciidoctor-pdf
----

=== Converting AsciiDoc to html5

Because Asciidoctor will default to the html5 backend you don't need to call it with any extra arguments.

[source, terminal]
----
asciidoctor example.adoc
# defaults to
asciidoctor -b html5 example.adoc
----

To see a list of all available backends you can call `asciidoctor --help`.

=== Converting AsciiDoc to pdf-files
After the installation of the gems you are ready to convert your AsciiDoc files to pdf-format.

[source, terminal]
----
asciidoctor-pdf example.adoc
----

=== Using the development version of Asciidoctor to create pdf-files

If you want to use the latest development version of asciidoctor to create your pdf-files you have to clone the asciidoctor-pdf https://github.com/asciidoctor/asciidoctor-pdf[repository] from Github.

[source, terminal]
----
include::res/terminal/clone_asciidoctor-pdf[]
----

To get the application ready you first need to install the dependencies. You might have to install the bundler gem first. 
// TODO(fap): should later link to gem explanation / installation guide in ruby doc

[source, terminal]
----
cd asciidoctor-pdf
bundle install
----

Now you can start using the latest version to convert your AsciiDoc.

[source, terminal]
----
./bin/asciidoctor-pdf /path/to/your/file.adoc
# or via bundler
bundle execute asciidoctor-pdf /path/to/your/file.adoc
----

=== Using Asciidoctor in a Gradle build file

==== Using AsciidoctorJ in a Gradle build

The easiest way to use Asciidoctor in a Gradle build is through the Asciidoctor Gradle Plugin.
It is based on AsciidoctorJ, which functions as a Java wrapper for Asciidoctor.

The following example `build.gradle` will convert your source files to html5.

[source, groovy]
----
include::res/gradle/asciidoctorj[]
----

You start the conversion by invoking the `asciidoctor` task.

[source, commandline]
----
include::res/gradle/asciidoctor_task[]
----

==== Using the Asciidoctor-Pdf gem in a Gradle build

You can use the latest Ruby version of Asciidoctor extensions directly in your Gradle build.
The following example shows how to use the asciidoctor-pdf gem.

[source, groovy]
----
include::res/gradle/asciidoctor-pdf[]
----

You start the conversion by invoking the `asciidoctor` task.

[source, commandline]
----
include::res/gradle/asciidoctor_task[]
----

==== Using the development version of Asciidoctor-Pdf in a Gradle build file
To use the development version of https://github.com/asciidoctor/asciidoctor-pdf[Asciidoctor-Pdf] in a Gradle build file you first need to build the gem.

[source, terminal]
----
include::res/terminal/clone_asciidoctor-pdf[]
include::res/terminal/build_gem[]
----
You can then find the `.gem` file under `/pkg`.
Copy it into your Gradle project under the folder `development-gems`.

We are going to use the JRuby and Asciidoctor Gradle plugin, so we need to declare them.

[source, groovy]
----
include::res/gradle/jruby_plugin[]
----

To use a local gem from Gradle, all dependencies of that gem have to be specified manually.
You can find the dependencies in `asciidoctor-pdf.gemspec`

[source, ruby]
----
include::res/gemspec/asciidoctor-pdf-dev_gemspec[]
----

You can then add them to your `build.gradle`.

[source, groovy]
----
include::res/gradle/asciidoctor-pdf-dev_dependencies[]
----

You need to override the jrubyPrepare task to use all of the declared dependencies plus the local gem.

[source, groovy]
----
include::res/gradle/customJRubyPrepare[]
----

Finally you have to make sure that the asciidoctor task depends on `customJRubyPrepare` and requires `asciidoctor-pdf`.

[source, groovy]
----
include::res/gradle/asciidoctor[]
----

Trigger the asciidoctor task to convert your AsciiDoc.

[source, terminal]
----
include::res/terminal/asciidoctor[]
----

