== Conversion with Asciidoctor

You will need a working ruby installation. For our installation guide see:
http://www.vogella.com/tutorials/Ruby/article.html

=== Asciidoctor installation

To convert your asciidoc files you need to install the asciidoctor gem.

[source, terminal]
----
gem install asciidoctor
----

If you want to be able to create pdf-files you can use the asciidoctor-pdf gem.

[source, terminal]
----
gem install --pre asciidoctor-pdf
----

=== Converting adoc to pdf-files
After the installation of the gems you are ready to convert your adoc files to pdf-format.

[source, terminal]
----
asciidoctor-pdf example.adoc
----

=== Using the development version of Asciidoctor to create pdf-files

If you want to use the latest development version of asciidoctor to create your pdf-files you have to clone the asciidoctor-pdf https://github.com/asciidoctor/asciidoctor-pdf[repository] from Github.

[source, terminal]
----
include::res/terminal/clone_asciidoctor-pdf[]
----

To get the application ready you first need to install the dependencies. You might have to install the bundler gem first. 
// TODO(fap): should later link to gem explanation / installation guide in ruby doc

[source, terminal]
----
cd asciidoctor-pdf
bundle install
----

Now you can start using the latest version to convert your AsciiDoc.

[source, terminal]
----
./bin/asciidoctor-pdf /path/to/your/file.adoc
----

=== Using the development version of Asciidoctor-Pdf in a Gradle build file
To use the development version of https://github.com/asciidoctor/asciidoctor-pdf[Asciidoctor-Pdf] in a Gradle build file you first need to build the Gem.

[source, terminal]
----
include::res/terminal/clone_asciidoctor-pdf[]
include::res/terminal/build_gem[]
----
You can then find the `.gem` file under `/pkg`.
Copy it into your Gradle project under the folder `development-gems`.

We are going to use the JRuby and Asciidoctor Gradle plugin, so we need to declare them.

[source, groovy]
----
include::res/gradle/jruby_plugin[]
----

To use a local Gem from Gradle, all dependencies of that Gem have to be specified manually.
You can find the dependencies in `asciidoctor-pdf.gemspec`

[source, ruby]
----
include::res/gemspec/asciidoctor-pdf_gemspec[]
----

You can then add them to your `build.gradle`.

[source, groovy]
----
include::res/gradle/asciidoctor-pdf_dependencies[]
----

You need to override the jrubyPrepare task to use all of the declared dependencies plus the local gem.

[source, groovy]
----
include::res/gradle/customJRubyPrepare[]
----

Finally you have to make sure that the asciidoctor task depends on `customJRubyPrepare` and requires `asciidoctor-pdf`.

[source, groovy]
----
include::res/gradle/asciidoctor[]
----

Trigger the asciidoctor task to convert your AsciiDoc.

[source, terminal]
----
include::res/terminal/asciidoctor[]
----

