== Conversion with Asciidoctor

You will need a working ruby installation. For our installation guide see:
http://www.vogella.com/tutorials/Ruby/article.html

=== Asciidoctor installation

To convert your asciidoc files you need to install the asciidoctor gem.

[source, terminal]
----
gem install asciidoctor
----

If you want to be able to create pdf-files you can use the asciidoctor-pdf gem.

[source, terminal]
----
gem install --pre asciidoctor-pdf
----

=== Converting adoc to pdf-files
After the installation of the gems you are ready to convert your adoc files to pdf-format.

[source, terminal]
----
asciidoctor-pdf example.adoc
----

=== Using the development version of Asciidoctor to create pdf-files

If you want to use the latest development version of asciidoctor to create your pdf-files you have to clone the asciidoctor-pdf https://github.com/asciidoctor/asciidoctor-pdf[repository] from Github.

[source, terminal]
----
git clone git@github.com:asciidoctor/asciidoctor-pdf.git
----

To get the application ready you first need to install the dependencies. You might have to install the bundler gem first. 
// TODO(fap): should later link to gem explanation / installation guide in ruby doc

[source, terminal]
----
cd asciidoctor-pdf
bundle install
----

Now you can start using the latest version to convert your AsciiDoc.

[source, terminal]
----
./bin/asciidoctor-pdf /path/to/your/file.adoc
----