== Settings for the PDF output

To see the links in the generated output use the following attribute in the header of you document.

[source,console]
----
:showlinks:
----

Also you can configure the label for a chapter via the `chapter-label` attribute, e.g. if you do not want any label you can use:

[source,console]
----
:chapter-label:
----

Unfortunately Asciidoctor does not add a page break before a  part if you use "book" as output.
See https://github.com/asciidoctor/asciidoctor-pdf/issues/329.
As workaround you have to put manual line breaks into it with `<<<`.

=== Styling the PDF output

In order to style the PDF output use the file _basic-theme.yml_ in folder _themes_.
In this file you can style the title page, the headings (h1, h2, h3, etc), the images and many more objects.

For example to style the heading do the following entry in the _basic-theme.yml_ file:

----
heading:
  font_style: bold
  h1:
    font_color: 999999
    font_style: italic
    align: right
----

A useful feature is to set a default width for images in the pdf output. To achieve this do the following entry:

----
image:
  width: 60%
----

To see all possible styling settings visit the https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc[Asciidoc theming guide].

