== Installation and setup of Jenkins

For most platforms you have native packages, see the https://jenkins.io/[Jenkins Homepage].

=== Installing of the Jenkins server on Ubuntu

Jenkins provides Debian/Ubuntu packages which install Jenkins and register Jenkins as start service. 
See the https://jenkins.io/doc/book/installing/#debian-ubuntu[Install Jenkins on Ubuntu description]
The Linux installation creates a _/etc/init.d/jenkins_ script which starts Jenkins automatically at boot time.

Jenkins stores all the settings, logs and build artifacts in its home directory. 
The default installation directory is _/var/lib/jenkins_ under Ubuntu.

==== Using the .war file to start Jenkins

Download the _jenkins.war_ file from https://jenkins.io/[Jenkins Homepage].
From this file you can start Jenkins directly via the command line with `java -jar jenkins*.war`.

If you start it locally, you find it running under the following URL: http://localhost:8080/

To run it in your Tomcat server, put the .war file into the _webapps_ directory. 
If you start Tomcat, your Jenkins installation will be available under 

....
http://localhost:8080/jenkins
....

[NOTE]
====
If the jenkins.war is deployed in your _webapps_ directory, but cannot be started and the tomcat manager says
_﻿FAIL - Application at context path /jenkins could not be started_, you may need to grant the permissons for `﻿JENKINS_HOME`.

[source,console]
----
﻿sudo mkdir .jenkins
﻿sudo
chown tomcat7:nogroup .jenkins
----

This makes the .jenkins folder writable and Jenkins can use it.
====



