== Jenkins backup and copying files

Jenkins stores all the settings, logs and build artifacts in its home directory. 
For example, in _/var/lib/jenkins_ under the default install location of Ubuntu.
		
To create a backup of your Jenkins setup, just copy this directory.
		
The _jobs_ directory contains the individual jobs configured in the Jenkins install. 
You can move a job from one Jenkins installation to another by copying the corresponding job directory. 
You can also copy a job directory to clone a job or rename the directory.

You only need to copy the `config.xml` file.
If you are using Git in the `jobs` directory you can use the following `.gitignore` file to exclude everything except this file.

[source,git]
----
# Ignore everything in /jobs
*
# Reinclude all folders in /jobs
!*/
# Ignore everything in the subfolders of /jobs
*/*
# Reinclude config.xml files in the first-level subfolders of /jobs
!*/config.xml
----
		
Click btn:[reload config] button in the Jenkins web user interface to force Jenkins to reload configuration from the disk.
		
See the following link for details: https://wiki.jenkins-ci.org/display/JENKINS/Administering+Jenkins

