[[freemarkertricks]]
== Useful FTL tricks

[[freemarkertricks_macro]]
=== Reuse common template fragments

When you find yourself copy-pasting common parts between templates a lot, you should probably use macros.

Continuing our last example, create a new folder called
`lib`
inside the
`templates`
directory, and there create a file called
`utils.ftl`
, with
this content:

[source,ftl]
----
include::res/tricks/macros/utils.ftl[]
----

Now you can simplify `helloworld.ftl` like this:

[source,ftl]
----
include::res/tricks/macros/helloworld.ftl[]
----

Another way of reusing template fragments is moving the common
fragment into
its own ftl file. Then just insert it with `<#include "lib/myfragment.ftl">`. This is less flexible than macros,
but simpler in concept: it mimics copy-pasting.

[[freemarkertricks_variables]]
=== Variables

You can define and assign content to variables inside the FTL files for easy reuse.

[source,ftl]
----
include::res/tricks/variables.ftl[]
----

[[freemarkertricks_macro]]
=== Handling null/undefined values

FreeMarker requires you to provide an explicit default for variables, so avoid
values that are
`null`
or undefined:

[source,ftl]
----
include::res/tricks/nulls.ftl[]
----

[[freemarkertricks_escape]]
=== Escape

When generating HTML, it's important to escape `&lt;`, `&amp;`,
etc. in values that were not meant to store HTML and can contain these
problematic characters.
You can apply such escaping like
`${message?html}`.
You can also ask FreeMarker to add
`?html`
to all
`${}`
-s in a section like this:

[source,ftl]
----
include::res/tricks/escaping.ftl[]
----

It's important to understand that
`#escape`
only affects the
`${}`
bits that are inside the enclosed section in the template file when you
look
at it in a text editor. That means,
`${}`
embracements which are in other templates or macros
called from there, won't be affected.

