== Connecting to MySQL

MySQL provides the `mysql` command line interface for administrative work.
To connect to the _MySQL_ database server use the following command:

[source,text]
----
# connect as root to MySQL server
mysql -u root -p
----

=== Initial setup of the dabase

To create a database and a user with access rights, use the following commands.

[source,sql]
====
CREATE DATABASE vogella_blog;
CREATE USER 'myblog'@'localhost' IDENTIFIED BY 'my_password';
GRANT ALL PRIVILEGES ON * . * TO 'myblog'@'localhost';
GRANT ALL ON vogella_blog.* TO 'myblog'@'localhost' IDENTIFIED BY 'my_password' WITH GRANT OPTION;
FLUSH PRIVILEGES;
====

Once you have created a database on this server you can also
connect directory to the database with the following command.

[source,text]
----
mysql db_name -u user -pmypassword
----

The default port of the database server is 3306.
For example, the Java JDBC connection string to connect to the iotcloud database would be
jdbc:mysql://localhost:3306/iotcloud. 

